// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Entry struct {
	Template string        `json:"template"`
	Fields   []*EntryField `json:"fields"`
}

type EntryField struct {
	Name  *string `json:"name,omitempty"`
	Value string  `json:"value"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewEntry struct {
	UserID   *string          `json:"userId,omitempty"`
	Fields   []*NewEntryField `json:"fields"`
	Template *string          `json:"template,omitempty"`
}

type NewEntryField struct {
	Name  *string `json:"name,omitempty"`
	Value string  `json:"value"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
