// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewWritingEntry struct {
	UserID     int                     `json:"userId"`
	Fields     []*NewWritingEntryField `json:"fields"`
	TemplateID int                     `json:"templateId"`
}

type NewWritingEntryField struct {
	Name  string  `json:"name"`
	Value *string `json:"value,omitempty"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
}

type WritingEntry struct {
	ID         int                  `json:"id"`
	UserID     int                  `json:"userId"`
	TemplateID int                  `json:"templateId"`
	Fields     []*WritingEntryField `json:"fields"`
}

type WritingEntryField struct {
	Name  string  `json:"name"`
	Value *string `json:"value,omitempty"`
}

type WritingTemplate struct {
	Title  string   `json:"title"`
	ID     int      `json:"id"`
	Fields []string `json:"fields"`
}
